steps:
- name: 'gcr.io/cloud-builders/kubectl'
  id: deploy-to-cluster
  args:
  - apply
  - -f
  - deployments/guestbook-ui-deployment.yaml
  - -f
  - deployments/guestbook-ui-svc.yaml

substitutions:
  YOUR_GCP_PROJECT_ID: big-query-406006
  YOUR_GKE_CLUSTER_NAME: autopilot-cluster-1

artifacts:
  objects:
    location: 'gs://your-bucket-name/cloudbuild/'
    paths:
    - 'deployments/guestbook-ui-deployment.yaml'
    - 'deployments/guestbook-ui-svc.yaml'
