steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'guestbook-ui-deployment.yaml', '-f', 'guestbook-ui-svc.yaml']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/guestbook-ui', 'guestbook-ui=gcr.io/heptio-images/ks-guestbook-demo:0.2']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['expose', 'deployment', 'guestbook-ui', '--type=LoadBalancer', '--name=guestbook-ui-lb']

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
