steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', 'autopilot-cluster-1', '--zone', 'us-central1']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployments/guestbook-ui-deployment.yaml', '-f', 'deployments/guestbook-ui-svc.yaml']

substitutions:
  _YOUR_GCP_PROJECT_ID: big-query-406006
  _YOUR_GKE_CLUSTER_NAME: autopilot-cluster-1

artifacts:
  objects:
    location: 'gs://logs-test1/cloudbuild/'
    paths:
    - 'deployments/guestbook-ui-deployment.yaml'
    - 'deployments/guestbook-ui-svc.yaml'

options:
  logging: logs-test1
