steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build-image
  args:
  - build
  - -t
  - gcr.io/big-query-406006/guestbook-ui:latest
  - .

- name: 'gcr.io/cloud-builders/kubectl'
  id: deploy-to-cluster
  args:
  - apply
  - -f
  - deployments/guestbook-ui-deployment.yaml
  - -f
  - deployments/guestbook-ui-svc.yaml

substitutions:
  _YOUR_GCP_PROJECT_ID: big-query-406006
  _YOUR_GKE_CLUSTER_NAME: autopilot-cluster-1

artifacts:
  objects:
    location: 'gs://your-bucket-name/cloudbuild/'
    paths:
    - 'deployments/guestbook-ui-deployment.yaml'
    - 'deployments/guestbook-ui-svc.yaml'

secrets:
  - versionedName: access-token
    secretEnv:
      ACCESS_TOKEN: $(cat /root/gcloud/application_default_credentials.json | base64 -w 0)
