steps:
- name: gcloud config
  id: setup-config
  entrypoint: /bin/bash
  args:
  - -c
  - |
    gcloud config set project big-query-406006
    gcloud auth configure-docker

- name: Build container image
  id: build-image
  entrypoint: docker
  args:
  - build
  - -t gcr.io/big-query-406006/guestbook-ui:latest
  - .

- name: Deploy to GKE
  id: deploy-to-cluster
  entrypoint: kubectl
  args:
  - apply
  - -f deployments/guestbook-ui-deployment.yaml
  - -f deployments/guestbook-ui-svc.yaml

substitutions:
  YOUR_GCP_PROJECT_ID: big-query-406006
  YOUR_GKE_CLUSTER_NAME: autopilot-cluster-1

artifacts:
  objects:
    location: 'gs://your-bucket-name/cloudbuild/'
    paths:
    - 'deployments/guestbook-ui-deployment.yaml'
    - 'deployments/guestbook-ui-svc.yaml'
